import { createContext } from "react";
import { PaginatedMedia, Setting, Permissions, Preset, Encode } from "./types";

const AppContext = createContext({
  directory: "",
  setDirectory: (directory: string) => {},
  tempDirectory: "",
  setTempDirectory: (tempDirectory: string) => {},
  data: {} as PaginatedMedia,
  setData: (data: any) => {},
  currentlyEncoding: "",
  setCurrentlyEncoding: (currentlyEncoding: string) => {},
  settings: [] as Setting[],
  setSettings: (settings: Setting[]) => {},
  sortModel: [] as any,
  setSortModel: (sortModel: any) => {},
  filterModel: {} as any,
  setFilterModel: (filterModel: any) => {},
  columnVisibilityModel: [] as any,
  setColumnVisibilityModel: (columnVisibilityModel: any) => {},
  paginationModel: {} as any,
  setPaginationModel: (paginationModel: any) => {},
  rowSelection: [] as any,
  setRowSelection: (rowSelection: any) => {},
  permissions: {} as Permissions,
  setPermissions: (permissions: Permissions) => {},
  action: "",
  setAction: (alignment: string) => {},
  presets: [] as Preset[],
  setPresets: (presets: Preset[]) => {},
  openEncodeModal: false,
  setOpenEncodeModal: (openEncodeModal: boolean) => {},
  selectedActionIndex: 0,
  setSelectedActionIndex: (actionIndex: number) => {},
  encodes: [] as Encode[],
  setEncodes: (encodes: Encode[]) => {},
  refreshQueued: false,
  setRefreshQueued: (refreshQueued: boolean) => {},
  refreshSettings: false,
  setRefreshSettings: (refreshSettings: boolean) => {},
});

export default AppContext;
